import { copyFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { homedir, platform } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  DOCKER_COMPOSE,
  DOCKER_COMPOSE_DIR,
  DOCKER_ENV_FILE,
  ENV_FILE,
  GATEWAY_PORT,
  OPENCLAW_HOME,
} from './config'
import type { CommandResult } from './openclaw'
import { runCommand } from './openclaw'

export type DockerStatus = {
  installed: boolean
  running: boolean
  gatewayContainer: boolean
  image: string
  composeFile: string
}

const DEFAULT_IMAGE = process.env.OPENCLAW_IMAGE || 'ghcr.io/openclaw/openclaw:latest'

const CANONICAL_COMPOSE = join(
  dirname(fileURLToPath(import.meta.url)),
  '../../../docker/docker-compose.yml'
)

export function ensureComposeLayout(): void {
  mkdirSync(DOCKER_COMPOSE_DIR, { recursive: true })
  if (!existsSync(DOCKER_COMPOSE) && existsSync(CANONICAL_COMPOSE)) {
    copyFileSync(CANONICAL_COMPOSE, DOCKER_COMPOSE)
  }
}

export async function getDockerStatus(): Promise<DockerStatus> {
  const info = await runCommand('docker', ['info'], 8_000)
  const ps = await runCommand('docker', ['ps', '--format', '{{.Names}}'], 8_000)
  return {
    installed: info.code !== 127 && !info.stderr.includes('command not found'),
    running: info.ok,
    gatewayContainer: ps.stdout.split('\n').some((n) => n.includes('openclaw-gateway')),
    image: DEFAULT_IMAGE,
    composeFile: DOCKER_COMPOSE,
  }
}

export async function ensureDockerDaemon(
  options: { openApp?: boolean } = {}
): Promise<CommandResult> {
  const probe = await runCommand('docker', ['info'], 5_000)
  if (probe.ok) return { ok: true, code: 0, stdout: 'Docker daemon ready', stderr: '' }

  if (options.openApp !== false && platform() === 'darwin') {
    await runCommand('open', ['-a', 'Docker'], 5_000)
  }

  for (let i = 0; i < 30; i++) {
    await sleep(2000)
    const retry = await runCommand('docker', ['info'], 5_000)
    if (retry.ok) {
      return {
        ok: true,
        code: 0,
        stdout: `Docker daemon ready after ${(i + 1) * 2}s`,
        stderr: '',
      }
    }
  }

  return {
    ok: false,
    code: 1,
    stdout: '',
    stderr: 'Docker daemon not available. Start Docker Desktop and retry.',
  }
}

export function writeDockerEnv(vars: Record<string, string>): void {
  mkdirSync(DOCKER_COMPOSE_DIR, { recursive: true })
  const lines = [
    '# Generated by OpenClaw Control — do not commit',
    `OPENCLAW_STATE_DIR=${OPENCLAW_HOME}`,
    `OPENCLAW_ENV_FILE=${ENV_FILE}`,
    `OPENCLAW_GATEWAY_PORT=${String(GATEWAY_PORT)}`,
    `OPENCLAW_IMAGE=${DEFAULT_IMAGE}`,
    `OLLAMA_API_KEY=${vars.OLLAMA_API_KEY || 'ollama-local'}`,
    `OPENCLAW_GATEWAY_TOKEN=${vars.OPENCLAW_GATEWAY_TOKEN || ''}`,
  ]
  writeFileSync(DOCKER_ENV_FILE, `${lines.join('\n')}\n`, 'utf8')
}

export async function dockerCompose(
  args: string[],
  env: Record<string, string> = {}
): Promise<CommandResult> {
  ensureComposeLayout()
  if (!existsSync(DOCKER_COMPOSE)) {
    return { ok: false, code: 1, stdout: '', stderr: `Missing compose file: ${DOCKER_COMPOSE}` }
  }

  return runCommand(
    'docker',
    ['compose', '--env-file', DOCKER_ENV_FILE, '-f', DOCKER_COMPOSE, ...args],
    180_000,
    { cwd: DOCKER_COMPOSE_DIR, env }
  )
}

export async function startDockerGateway(
  token: string
): Promise<CommandResult & { health?: boolean }> {
  writeDockerEnv({
    OPENCLAW_GATEWAY_TOKEN: token,
    OLLAMA_API_KEY: process.env.OLLAMA_API_KEY || 'ollama-local',
  })

  const daemon = await ensureDockerDaemon({ openApp: true })
  if (!daemon.ok) return daemon

  await dockerCompose(['pull', 'openclaw-gateway'])
  const up = await dockerCompose(['up', '-d', '--remove-orphans', 'openclaw-gateway'])
  if (!up.ok) return up

  const healthy = await waitForGatewayHealth(90_000)
  return { ...up, health: healthy }
}

export async function stopDockerGateway(): Promise<CommandResult> {
  if (!existsSync(DOCKER_COMPOSE)) {
    return { ok: true, code: 0, stdout: 'No compose file — nothing to stop', stderr: '' }
  }
  writeDockerEnv({ OPENCLAW_GATEWAY_TOKEN: process.env.OPENCLAW_GATEWAY_TOKEN || '' })
  return dockerCompose(['down'])
}

export async function getDockerLogs(tail = 80): Promise<string> {
  const result = await dockerCompose(['logs', '--tail', String(tail), 'openclaw-gateway'])
  return result.stdout || result.stderr || 'No logs'
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms))
}

async function waitForGatewayHealth(timeoutMs: number): Promise<boolean> {
  const deadline = Date.now() + timeoutMs
  const url = `http://127.0.0.1:${GATEWAY_PORT}/healthz`
  while (Date.now() < deadline) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(3000) })
      if (res.ok) return true
    } catch {
      // keep waiting
    }
    await sleep(2000)
  }
  return false
}

export function resolveOpenclawEnv(): NodeJS.ProcessEnv {
  const env = { ...process.env, OPENCLAW_STATE_DIR: OPENCLAW_HOME }
  const fnmNode = join(homedir(), '.local/share/fnm/node-versions/v24.15.0/installation/bin')
  if (existsSync(join(fnmNode, 'openclaw'))) {
    env.PATH = `${fnmNode}:${env.PATH || ''}`
  }
  return env
}
